name: CI
on: pull_request

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Check linting rules
        run: yarn lint

      - name: Check types
        run: yarn lint:tsc

  integration-tests:
    name: Run tests
    runs-on: ubuntu-20.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Set environment variables
        run: |
          echo "DATABASE_URL=postgresql://postgres:password@localhost:5432/db" >> $GITHUB_ENV
          echo "SECRET_PASSWORD=abcdefghijklmnopqrstuvwxyz1234567890" >> $GITHUB_ENV

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run db
        run: |
          docker pull postgres:14.2
          docker run -d -p 5432:5432 -e POSTGRES_PASSWORD=password -e POSTGRES_DB=db postgres:14.2
          yarn wait-on --timeout 60000 tcp:localhost:5432

      - name: Deploy migrations
        run: yarn prisma migrate deploy

      - name: Install playwright dependencies
        run: yarn playwright install --with-deps chromium

      - name: Run tests
        run: yarn test

      - name: Upload artifact playwright-report
        if: ${{ success() || failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: ./playwright-report
